"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-s(ae385z%5z*sj3%)tfa-&d-!dwomn@z6x0#wf4-o5(*&nir3$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bookshelf',
    'relationship_app',
    'csp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'csp.middleware.CSPMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = '/relationships/books/' # Redirect to the book list after login

AUTH_USER_MODEL = 'bookshelf.CustomUser'


import os
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Ensures the CSRF cookie is only sent over HTTPS in production.
CSRF_COOKIE_SECURE = True

# Ensures the session cookie is only sent over HTTPS in production.
SESSION_COOKIE_SECURE = True

# Enables the browser's built-in XSS protection.
# Modern browsers have this, but it's good for older ones.
SECURE_BROWSER_XSS_FILTER = True

# Step 1: Configure Django for HTTPS Support
# Redirects all non-HTTPS requests to HTTPS.
# Your web server (like Nginx) should also be configured to do this.
SECURE_SSL_REDIRECT = True

# Step 1: Configure HSTS (HTTP Strict Transport Security)
# Instructs the browser to only access the site via HTTPS for the next year.
# This reduces the risk of man-in-the-middle attacks.
SECURE_HSTS_SECONDS = 31536000  # 1 year in seconds
# Ensures that the HSTS policy applies to all subdomains of your site.
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# Allows your site to be submitted to browser preload lists for HSTS.
SECURE_HSTS_PRELOAD = True

# Prevents the browser from guessing content types, which can be a security risk.
SECURE_CONTENT_TYPE_NOSNIFF = True

# Prevents your site from being rendered in an <iframe>, protecting against clickjacking.
X_FRAME_OPTIONS = 'DENY'

# --- CONTENT SECURITY POLICY ---
# By default, this is very strict. It only allows content (scripts, styles, etc.)
# to be loaded from the same origin ('self').
CSP_DEFAULT_SRC = ("'self'",)
